import { useEffect, useMemo, useState } from 'react'
import { CircleMarker, Polyline, Popup, useMap, useMapEvents } from 'react-leaflet'
import { Accessibility, AlertTriangle, CheckCircle2, Crosshair, Navigation, Route, Sparkles, X } from 'lucide-react'
import { supabase } from '../lib/supabase'

type Location = [number, number]
type Report = { id: string; latitude: number; longitude: number; barrier_type: string; description: string | null; created_at: string }
type RouteOption = { coordinates: Location[]; distance: number; duration: number; riskScore: number; nearbyBarriers: Report[]; blocked: boolean }
type Props = { userLocation: Location | null }
const ROUTING_URL = 'https://routing.openstreetmap.de/routed-foot/route/v1/driving'

function haversineMeters(a: Location, b: Location) { const R = 6371000; const lat1 = (a[0] * Math.PI) / 180; const lat2 = (b[0] * Math.PI) / 180; const dLat = ((b[0] - a[0]) * Math.PI) / 180; const dLng = ((b[1] - a[1]) * Math.PI) / 180; const x = Math.sin(dLat / 2) ** 2 + Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLng / 2) ** 2; return 2 * R * Math.atan2(Math.sqrt(x), Math.sqrt(1 - x)) }
function minDistanceToRoute(report: Report, coordinates: Location[]) { const point: Location = [report.latitude, report.longitude]; let minimum = Number.POSITIVE_INFINITY; for (let index = 0; index < coordinates.length; index += 3) minimum = Math.min(minimum, haversineMeters(point, coordinates[index])); return minimum }
function barrierWeight(type: string) { if (type === 'Blocked Ramp' || type === 'Inaccessible Entrance') return 5; if (type === 'Narrow Pathway' || type === 'Steep Entrance' || type === 'Missing Accessibility Facility') return 3; if (type === 'Accessibility Uncertain') return 1; return 0 }
function isBlockingBarrier(type: string) { return type === 'Blocked Ramp' || type === 'Inaccessible Entrance' }
function formatDistance(meters: number) { return meters < 1000 ? `${Math.round(meters)} m` : `${(meters / 1000).toFixed(1)} km` }
function formatDuration(seconds: number) { const minutes = Math.max(1, Math.round(seconds / 60)); if (minutes < 60) return `${minutes} min`; const hours = Math.floor(minutes / 60); const remaining = minutes % 60; return remaining ? `${hours} hr ${remaining} min` : `${hours} hr` }
function DestinationPicker({ selecting, onPick }: { selecting: boolean; onPick: (location: Location) => void }) { useMapEvents({ click(event) { if (selecting) onPick([event.latlng.lat, event.latlng.lng]) } }); return null }

export default function AccessibleRoutePlanner({ userLocation }: Props) {
  const map = useMap(); const [selecting, setSelecting] = useState(false); const [destination, setDestination] = useState<Location | null>(null); const [routes, setRoutes] = useState<RouteOption[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [selectedRoute, setSelectedRoute] = useState(0); const [open, setOpen] = useState(false)
  const recommendedIndex = useMemo(() => routes.length ? routes.reduce((best, route, index) => route.blocked ? best : route.riskScore * 1000 + route.duration / 60 < routes[best].riskScore * 1000 + routes[best].duration / 60 ? index : best, routes[0]?.blocked ? 0 : 0) : 0, [routes])

  async function calculateRoutes(start: Location, end: Location) {
    setLoading(true); setError('')
    try {
      const coordinates = `${start[1]},${start[0]};${end[1]},${end[0]}`
      const response = await fetch(`${ROUTING_URL}/${coordinates}?alternatives=3&steps=true&overview=full&geometries=geojson`)
      if (!response.ok) throw new Error('The walking route service is unavailable right now.')
      const payload: unknown = await response.json(); const rawRoutes = (payload as { routes?: unknown[] }).routes ?? []
      if (!rawRoutes.length) throw new Error('No walking route could be found between these locations.')
      const allCoordinates: Location[] = rawRoutes.flatMap((route) => { const geometry = (route as { geometry?: { coordinates?: unknown[] } }).geometry; return (geometry?.coordinates ?? []).flatMap((pair) => { if (!Array.isArray(pair) || pair.length < 2) return []; const lng = Number(pair[0]); const lat = Number(pair[1]); return Number.isFinite(lat) && Number.isFinite(lng) ? [[lat, lng] as Location] : [] }) })
      if (!allCoordinates.length) throw new Error('The route service returned no map geometry.')
      const lats = allCoordinates.map(([lat]) => lat); const lngs = allCoordinates.map(([, lng]) => lng); const padding = 0.002
      const { data: reports, error: reportsError } = await supabase.rpc('get_map_reports', { p_min_lat: Math.min(...lats) - padding, p_max_lat: Math.max(...lats) + padding, p_min_lng: Math.min(...lngs) - padding, p_max_lng: Math.max(...lngs) + padding, p_limit: 500 })
      if (reportsError) console.warn('Could not load barrier reports for routing:', reportsError)
      const confirmedReports = (reports ?? []) as Report[]
      const scoredRoutes: RouteOption[] = rawRoutes.map((rawRoute) => { const typedRoute = rawRoute as { geometry?: { coordinates?: unknown[] }; distance?: number; duration?: number }; const routeCoordinates: Location[] = (typedRoute.geometry?.coordinates ?? []).flatMap((pair) => { if (!Array.isArray(pair) || pair.length < 2) return []; const lng = Number(pair[0]); const lat = Number(pair[1]); return Number.isFinite(lat) && Number.isFinite(lng) ? [[lat, lng] as Location] : [] }); const nearbyBarriers = confirmedReports.filter((report) => minDistanceToRoute(report, routeCoordinates) <= 70 && barrierWeight(report.barrier_type) > 0); const blocked = nearbyBarriers.some((report) => isBlockingBarrier(report.barrier_type) && minDistanceToRoute(report, routeCoordinates) <= 35); const riskScore = blocked ? 100000 : nearbyBarriers.reduce((total, report) => { const weight = barrierWeight(report.barrier_type); const distance = minDistanceToRoute(report, routeCoordinates); return total + (distance <= 30 ? weight : weight * 0.5) }, 0); return { coordinates: routeCoordinates, distance: Number(typedRoute.distance ?? 0), duration: Number(typedRoute.duration ?? 0), riskScore, nearbyBarriers, blocked } })
      setRoutes(scoredRoutes); const viable = scoredRoutes.map((route, index) => ({ route, index })).filter(({ route }) => !route.blocked); const best = (viable.length ? viable : scoredRoutes.map((route, index) => ({ route, index }))).reduce((bestItem, item) => item.route.riskScore * 1000 + item.route.duration / 60 < bestItem.route.riskScore * 1000 + bestItem.route.duration / 60 ? item : bestItem).index; setSelectedRoute(best); setOpen(true); if (scoredRoutes[best]?.coordinates.length) map.fitBounds(scoredRoutes[best].coordinates, { padding: [80, 80], maxZoom: 17 })
    } catch (routeError) { console.error('Route calculation failed:', routeError); setRoutes([]); setError(routeError instanceof Error ? routeError.message : 'Could not calculate an accessible route.'); setOpen(true) } finally { setLoading(false) }
  }
  useEffect(() => { if (destination && userLocation) void calculateRoutes(userLocation, destination) }, [destination, userLocation])
  useEffect(() => { const route = routes[selectedRoute]; if (route?.coordinates.length) map.fitBounds(route.coordinates, { padding: [90, 90], maxZoom: 17 }) }, [map, routes, selectedRoute])
  function clearRoute() { setDestination(null); setRoutes([]); setError(''); setSelecting(false); setOpen(false) }
  const selected = routes[selectedRoute]; const recommended = routes[recommendedIndex]

  return <>
    <DestinationPicker selecting={selecting} onPick={(location) => { setDestination(location); setSelecting(false) }} />
    {routes.map((route, index) => <Polyline key={`route-${index}`} positions={route.coordinates} pathOptions={{ color: index === recommendedIndex ? '#16a34a' : route.blocked ? '#dc2626' : '#64748b', weight: index === selectedRoute ? 8 : 4, opacity: index === recommendedIndex ? 0.95 : route.blocked ? 0.58 : 0.42, dashArray: index === recommendedIndex ? undefined : '9 9', lineCap: 'round', lineJoin: 'round' }} eventHandlers={{ click: () => setSelectedRoute(index) }} />)}
    {destination && <CircleMarker center={destination} radius={10} pathOptions={{ color: '#0f172a', weight: 4, fillColor: '#fff', fillOpacity: 1 }}><Popup><strong>Destination</strong></Popup></CircleMarker>}
    <div className="absolute left-4 top-[150px] z-[1000] w-[min(400px,calc(100vw-32px))] sm:top-32">
      {!open && <button type="button" onClick={() => setOpen(true)} className="access-enter group flex w-full items-center gap-3 rounded-[1.25rem] border border-white/80 bg-slate-950 px-4 py-3.5 text-left text-white shadow-2xl shadow-slate-900/20 transition hover:-translate-y-0.5"><span className="access-pulse flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-emerald-500"><Accessibility size={20} /></span><span className="min-w-0"><span className="flex items-center gap-2 text-sm font-black">Find an accessible route <Sparkles size={14} className="text-emerald-300" /></span><span className="mt-0.5 block text-xs text-slate-300">Compare routes against community accessibility signals</span></span></button>}
      {open && <div className="access-enter overflow-hidden rounded-[1.5rem] border border-white/80 bg-white/95 p-4 shadow-2xl shadow-slate-900/20 backdrop-blur-xl">
        <div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-emerald-50 text-emerald-700"><Route size={17} /></span><h2 className="text-sm font-black text-slate-950">Accessible route planner</h2></div><p className="mt-2 text-xs leading-5 text-slate-500">ACCESS compares walking alternatives with confirmed community reports.</p></div><button type="button" onClick={clearRoute} className="rounded-xl p-2 text-slate-400 hover:bg-slate-100" aria-label="Close route planner"><X size={17} /></button></div>
        {!userLocation && <div className="mt-3 rounded-2xl border border-amber-200 bg-amber-50 p-3 text-xs leading-5 text-amber-900"><div className="flex gap-2"><AlertTriangle size={16} className="mt-0.5 shrink-0" /><span>Use “Find my location” first so ACCESS knows your starting point.</span></div></div>}
        <button type="button" onClick={() => { setSelecting(true); setOpen(true) }} disabled={!userLocation || loading} className="mt-3 flex w-full items-center justify-center gap-2 rounded-2xl bg-slate-950 px-4 py-3 text-sm font-bold text-white shadow-lg shadow-slate-950/10 transition hover:-translate-y-0.5 disabled:opacity-50"><Crosshair size={17} />{selecting ? 'Tap your destination on the map' : destination ? 'Choose a different destination' : 'Choose destination on map'}</button>
        {selecting && <div className="mt-2 rounded-xl bg-emerald-50 px-3 py-2 text-center text-[11px] font-bold text-emerald-800">Tap anywhere on the map to set your destination</div>}
        {loading && <div className="access-shimmer mt-3 rounded-2xl bg-slate-900 p-3 text-sm font-semibold text-white">Finding routes and checking accessibility signals…</div>}
        {error && !loading && <div className="mt-3 rounded-2xl border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</div>}
        {selected && !loading && <div className="mt-3 space-y-2.5">
          <div className={`rounded-2xl border p-3.5 ${recommended?.blocked ? 'border-amber-200 bg-amber-50' : 'border-emerald-200 bg-gradient-to-br from-emerald-50 to-white'}`}><div className="flex items-start gap-2.5"><div className="mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-xl bg-emerald-500 text-white shadow-sm"><CheckCircle2 size={17} /></div><div><div className="flex items-center gap-2"><p className="text-sm font-black text-emerald-950">Recommended route</p><span className="rounded-full bg-emerald-100 px-2 py-0.5 text-[9px] font-black uppercase tracking-wider text-emerald-700">lowest risk</span></div><p className="mt-1 text-xs leading-5 text-emerald-800">{recommended?.nearbyBarriers.length ? `${recommended.nearbyBarriers.length} reported barrier${recommended.nearbyBarriers.length === 1 ? '' : 's'} near this option.` : 'No confirmed accessibility barriers detected near this option.'}</p></div></div></div>
          {selected.blocked && <div className="rounded-2xl border border-red-200 bg-red-50 p-3"><p className="flex items-center gap-2 text-xs font-black text-red-900"><AlertTriangle size={15} />This route has a blocking accessibility report.</p><p className="mt-1 text-[11px] leading-5 text-red-800">ACCESS recommends another available route instead.</p></div>}
          <div className="grid grid-cols-2 gap-2"><div className="rounded-2xl bg-slate-50 p-3"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Walking time</p><p className="mt-1 text-lg font-black text-slate-950">{formatDuration(selected.duration)}</p></div><div className="rounded-2xl bg-slate-50 p-3"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Distance</p><p className="mt-1 text-lg font-black text-slate-950">{formatDistance(selected.distance)}</p></div></div>
          <div className="space-y-2">{routes.map((route, index) => <button type="button" key={`route-card-${index}`} onClick={() => setSelectedRoute(index)} className={`w-full rounded-2xl border p-3 text-left transition hover:-translate-y-0.5 ${index === selectedRoute ? 'border-slate-950 bg-slate-950 text-white shadow-lg' : index === recommendedIndex ? 'border-emerald-200 bg-emerald-50/60 text-slate-950' : route.blocked ? 'border-red-200 bg-red-50 text-slate-950' : 'border-slate-200 bg-white hover:bg-slate-50'}`}><div className="flex items-center justify-between gap-3"><div><div className="flex items-center gap-2"><p className="text-xs font-black">{index === recommendedIndex ? 'Recommended' : `Alternative ${index}`}</p>{route.blocked ? <AlertTriangle size={13} className="text-red-500" /> : index === recommendedIndex && <CheckCircle2 size={13} className="text-emerald-500" />}</div><p className="mt-1 text-xs opacity-70">{formatDuration(route.duration)} · {formatDistance(route.distance)}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${route.blocked ? 'bg-red-100 text-red-700' : route.nearbyBarriers.length === 0 ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-800'}`}>{route.blocked ? 'Blocked' : route.nearbyBarriers.length === 0 ? 'Clear' : `${route.nearbyBarriers.length} barrier${route.nearbyBarriers.length === 1 ? '' : 's'}`}</span></div></button>)}</div>
          {selected.nearbyBarriers.length > 0 && <div className="rounded-2xl border border-amber-200 bg-amber-50 p-3"><p className="flex items-center gap-2 text-xs font-black text-amber-950"><AlertTriangle size={15} />Reports near this route</p><div className="mt-2 space-y-2">{selected.nearbyBarriers.slice(0, 3).map((report) => <div key={report.id} className="rounded-xl bg-white/60 p-2 text-xs leading-5 text-amber-900"><strong>{report.barrier_type}</strong>{report.description ? ` — ${report.description}` : ''}</div>)}</div></div>}
          <div className="flex items-center gap-2 border-t border-slate-100 pt-2 text-[10px] leading-4 text-slate-400"><Navigation size={13} />OpenStreetMap walking data · community reports are advisory</div>
        </div>}
      </div>}
    </div>
  </>
}
